return {
 ["name:Chaparral Pro#786431"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro/B:mode=node;script=latn;language=dflt;#b#786433"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Semibold.otf", false },
 ["name:Chaparral Pro/B:mode=node;script=latn;language=dflt;#b#786434"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Semibold.otf", false },
 ["name:Chaparral Pro/B:mode=node;script=latn;language=dflt;+tlig;#b#1630536"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Semibold.otf", false },
 ["name:Chaparral Pro/B:mode=node;script=latn;language=dflt;+tlig;#b#786432"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Semibold.otf", false },
 ["name:Chaparral Pro/BI:mode=node;script=latn;language=dflt;#bi#786433"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-SemiboldIt.otf", false },
 ["name:Chaparral Pro/BI:mode=node;script=latn;language=dflt;#bi#786434"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-SemiboldIt.otf", false },
 ["name:Chaparral Pro/I:mode=node;script=latn;language=dflt;#i#786433"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Italic.otf", false },
 ["name:Chaparral Pro/I:mode=node;script=latn;language=dflt;#i#786434"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Italic.otf", false },
 ["name:Chaparral Pro:mode=node;#786430"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;#786434"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;#786433"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;#786434"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#1630536"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#360448"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#458752"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#504625"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#524288"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#655360"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#720896"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Chaparral Pro:mode=node;script=latn;language=dflt;+tlig;#786432"]={ "c:/Users/Blais/AppData/Local/Microsoft/Windows/Fonts/ChaparralPro-Regular.otf", false },
 ["name:Josefin Sans#786431"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#1132462"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#1630536"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#786432"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#786433"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#786434"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/B:mode=node;script=latn;language=dflt;#b#943718"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Bold.ttf", false },
 ["name:Josefin Sans/BI:mode=node;script=latn;language=dflt;#bi#786433"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-BoldItalic.ttf", false },
 ["name:Josefin Sans/BI:mode=node;script=latn;language=dflt;#bi#786434"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-BoldItalic.ttf", false },
 ["name:Josefin Sans/I:mode=node;script=latn;language=dflt;#i#717619"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Italic.ttf", false },
 ["name:Josefin Sans/I:mode=node;script=latn;language=dflt;#i#786433"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Italic.ttf", false },
 ["name:Josefin Sans/I:mode=node;script=latn;language=dflt;#i#786434"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Italic.ttf", false },
 ["name:Josefin Sans:mode=node;#786430"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;#786434"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#1132462"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#1630536"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#717619"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#786432"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#786433"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#786434"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Josefin Sans:mode=node;script=latn;language=dflt;#943718"]={ "c:/texlive/2025/texmf-dist/fonts/truetype/public/josefin/JosefinSans-Regular.ttf", false },
 ["name:Latin Modern Mono#786431"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono/B:mode=node;script=latn;language=dflt;#b#786433"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono/BI:mode=node;script=latn;language=dflt;#bi#786433"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono/I:mode=node;script=latn;language=dflt;#i#786433"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono10-italic.otf", false },
 ["name:Latin Modern Mono/I:mode=node;script=latn;language=dflt;#i#786434"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono10-italic.otf", false },
 ["name:Latin Modern Mono:mode=node;#786430"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono:mode=node;#786434"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono:mode=node;script=latn;language=dflt;#786433"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
 ["name:Latin Modern Mono:mode=node;script=latn;language=dflt;#786434"]={ "c:/texlive/2025/texmf-dist/fonts/opentype/public/lm/lmmono12-regular.otf", false },
}